### ISSUE TITLE
Make the game more game-like

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#21]
I.e. include a background, score timer etc.

**Comment by YvanKlaver** [comment]
Will look into an efficient way for getting a background. Currently we redraw the entire scene every iteration, this is kind of a waste if we have a static background but might be the only option as openGL automatically takes blending properties in account, whether they are used it doesn't know.

Also score/timer is gonna be an issue as it is uses fonts which is not a thing in openGL. We might need another package for that.  I came across something called openFonts a few days back which might be good. Anyway if we get REALLY desperate we might add the GLUT library but I'll try to avoid it as much as possible as apparently it is called a 'monstrosity' on the internet because of it's size.

We could also use the openGL-tutorial way but for that we need to fix GLSL (shaders) and it's kind of a hassle to execute.

**Comment by YvanKlaver** [comment]
Fonts is a step closer. Texturing with shaders has been fixed thus we should be able to render fonts on screen in an efficient manner.

**Comment by zwyber** [comment]
It is a game now!
