### ISSUE TITLE
Resize universe with window size?

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#27]
Make the universe as big as the window?

**Comment by YvanKlaver** [comment]
Will implement this, maybe leave the fixed independent universe as an option. It's nice for debugging. Will probably overload the constructor with an extra flag for that, but definitely make the auto-resize standard.

**Comment by YvanKlaver** [comment]
Universe is now coupled to a Window. The following flags can be used to decide how Universe size is manipulated when the Window gets resized:
- FIXED_SIZE_UNIVERSE: The Universe will not change its size when Window changes size.
- AUTO_SIZE_UNIVERSE: The Universe will always fit the Window on the set pixRatio. Resize of Window directly affects Universe proportional.
- PROP_SIZE_UNIVERSE: The Universe is not forced to fit Window. Resize of Window will affect Universe proportional.
- NO_RESIZE: Window is not saleable by user but only via code, otherwise identical to PROP_SIZE_UNIVERSE.
- ZOOM_UNIVERSE: The Universe is not forced to fit Window. Resize of Window will affect pixRatio proportional such that smallest dimension will fit.

Now Window does need access to Universe so Window has a Universe pointer called boundUniverse. Can be set by bindUniverse or constructors.
