### ISSUE TITLE
Inelastic collisions cause objects to stick to the wall

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#30]
Must not allow inelastic collisions with a wall, somehow.

**Comment by YvanKlaver** [comment]
In advance apologies for bringing this up AGAIN, it is not meant as disagreement but rather as reconsideration now we start to face more problems:
- For this I think it might still be a good idea to change the wall collision from, mirror object to changing velocity direction along wall normal to fit normal direction. 
- I mean mirror objects is clever and all but currently we are looking for efficiency and functionality. Efficiency is by no doubt less with the mirror object and functionality was better but starts to get more drawbacks as we progress. 
- The alternative process will also prevent objects from leaving the universe box, as it changes the wall collision region from one radius unit to infinity without having processing drawback. 

Also I'd change the bounciness factor used in the calculation from the most inelastic object to a square root of both objects squared (or just averaged). This will give the possibility of having the wall object at fully elastic and not having the object sticking to it (WHICH IT ALWAYS WILL AT BOUNCINESS = 0) but still having a not completely elastic collision.

**Comment by YvanKlaver** [comment]
We now combined inelastic with elastic collisions. By working out the inelastic scattering I noticed a slight similarity with the formula we used for elastic scattering anyway. By working out the elastic formula to expressions that are easy to visualize iit seemed to be EXACTLY the same except for one scalar: `2 * A_m/(A_m+B_m) = (1+coeff)*A_m/(A_m+B_m)`. 

Also the original inelastic part contained a consistent typo for *_x instead of *_v. Fixing this however did not fix the issue of sticking together (entirely).
