### ISSUE TITLE
New energy generates over time

### ISSUE THREAD

**Issue by YvanKlaver** [zwyber/pie#32]
From `test_07()` it becomes apparent that slight discontinuities happen in the total energy, mostly in the kinetic force. Because of the discrete characteristics I'd suspect collisions to be the cause of such jumps.

To see for yourself: use `test_07()` to generate file `test07.csv` and plot this with `PlotTest06.m` (yes I know, I messed up the numbering).

For further reading on conservation of energy in gravitational particle systems I'd suggest to read up on: "Classical Dynamics of Particles and Systems" by S.T. Thornton and J.B. Marion. Chapter 5 discusses Gravitational forces.

**Comment by zwyber** [comment]
After discussion: It appears that the gain in energy is due to the (relatively) large accelerations when two objects are close to each other. After the collision the entire system will have gained energy a bit due to this.

Sort of fixed this by switching to a midpoint method for the differential equation solver. Still first order, but behaves a bit better!

**Comment by YvanKlaver** [comment]
thought of a reason this could happen, we push out objects from each other during collisions which means you generate potential energy from nothing.
